version: "3"


secrets:
  anvil_fork_url_holesky:
    file: anvil_fork_url_holesky.txt


networks:
  lambada-coprocessor-network:
    name: lambada-coprocessor-network
    driver: bridge

services:

  anvil:
    build:
      context: .
      dockerfile: Dockerfile-anvil
    container_name: anvil
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - ./tests/anvil/avs-and-eigenlayer-deployed-anvil-state.json:/root/.anvil/state.json
      - ./:/cartesi-lambada-coprocessor/

    command: /cartesi-lambada-coprocessor/tests/anvil/run-anvil-holesky.sh

    healthcheck:

      test: bash -c "[ -f /cartesi-lambada-coprocessor/contracts/script/output/lambada_coprocessor_deployment_output_holesky.json ]"
      interval: 3s
      retries: 20
      start_period: 15s

    networks:
      - lambada-coprocessor-network

    secrets:
      - anvil_fork_url_holesky


  aggregator-storage:
    image: mysql
    volumes:
      - ./tests/mysql/script:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - lambada-coprocessor-network
    
  aggregator:
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    container_name: lambada-coprocessor-aggregator
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      anvil:
        condition: service_healthy
      aggregator-storage:
        condition: service_started
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: 
      - --config 

      - tests/nodes/aggregator/config-holesky.yaml

      - --private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
      - --database-password
      - password
    networks:
      - lambada-coprocessor-network
    healthcheck:
      test: bash -c "[ cat < /dev/null > /dev/tcp/0.0.0.0/8080 ]"
      interval: 10s
      retries: 200
      start_period: 15s


  machine1:
    image: ghcr.io/zippiehq/cartesi-lambada:latest
    container_name: lambada-coprocessor-machine1
    ports:
      - 127.0.0.1:5001:5001
      - 127.0.0.1:3001:3033
    volumes:
      - ./tests/nodes/operators/1/data:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator1:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator1
    depends_on:
      aggregator:
        condition: service_healthy
      machine1:
        condition: service_started
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: tests/nodes/operators/1/run-holesky.sh
    networks:
      - lambada-coprocessor-network

  machine2:
    image: ghcr.io/zippiehq/cartesi-lambada:latest
    container_name: lambada-coprocessor-machine2
    ports:
      - 127.0.0.1:5002:5001
      - 127.0.0.1:3002:3033
    volumes:
      - ./tests/nodes/operators/2/data:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator2:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator2
    depends_on:
      aggregator:
        condition: service_healthy
      machine2:
        condition: service_started
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: tests/nodes/operators/2/run-holesky.sh
    networks:
      - lambada-coprocessor-network

  machine3:
    image: ghcr.io/zippiehq/cartesi-lambada:latest
    container_name: lambada-coprocessor-machine3
    ports:
      - 127.0.0.1:5003:5001
      - 127.0.0.1:3003:3033
    volumes:
      - ./tests/nodes/operators/3/data:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator3:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator3
    depends_on:
      aggregator:
        condition: service_healthy
      machine3:
        condition: service_started
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: tests/nodes/operators/3/run-holesky.sh
    networks:
      - lambada-coprocessor-network
