FROM debian
RUN apt-get update && apt-get install -y git curl bash

RUN curl -L https://foundry.paradigm.xyz | bash
RUN bash -c 'source /root/.profile && foundryup'
RUN cp -r /root/.foundry/bin/* /usr/local/bin/
RUN adduser --uid 1000 foundry

ENTRYPOINT ["/bin/sh", "-c"]