# fly.toml app configuration file generated for cartesi-lambada-coprocessor on 2024-10-04T09:04:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cartesi-lambada-coprocessor'
primary_region = 'jnb'

[build]
  [build.args]
    GO_VERSION = '1.21'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
