// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zippiehq/cartesi-lambada-coprocessor/operator (interfaces: AggregatorRpcClienter)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/rpc_client.go -package=mocks github.com/zippiehq/cartesi-lambada-coprocessor/operator AggregatorRpcClienter
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	aggregator "github.com/zippiehq/cartesi-lambada-coprocessor/aggregator"
	types "github.com/zippiehq/cartesi-lambada-coprocessor/aggregator/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAggregatorRpcClienter is a mock of AggregatorRpcClienter interface.
type MockAggregatorRpcClienter struct {
	ctrl     *gomock.Controller
	recorder *MockAggregatorRpcClienterMockRecorder
}

// MockAggregatorRpcClienterMockRecorder is the mock recorder for MockAggregatorRpcClienter.
type MockAggregatorRpcClienterMockRecorder struct {
	mock *MockAggregatorRpcClienter
}

// NewMockAggregatorRpcClienter creates a new mock instance.
func NewMockAggregatorRpcClienter(ctrl *gomock.Controller) *MockAggregatorRpcClienter {
	mock := &MockAggregatorRpcClienter{ctrl: ctrl}
	mock.recorder = &MockAggregatorRpcClienterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregatorRpcClienter) EXPECT() *MockAggregatorRpcClienterMockRecorder {
	return m.recorder
}

// GetBatchTasks mocks base method.
func (m *MockAggregatorRpcClienter) GetBatchTasks(arg0 uint32) ([]types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatchTasks", arg0)
	ret0, _ := ret[0].([]types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatchTasks indicates an expected call of GetBatchTasks.
func (mr *MockAggregatorRpcClienterMockRecorder) GetBatchTasks(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatchTasks", reflect.TypeOf((*MockAggregatorRpcClienter)(nil).GetBatchTasks), arg0)
}

// SendSignedTaskResponseToAggregator mocks base method.
func (m *MockAggregatorRpcClienter) SendSignedTaskResponseToAggregator(arg0 *aggregator.SignedTaskResponse) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendSignedTaskResponseToAggregator", arg0)
}

// SendSignedTaskResponseToAggregator indicates an expected call of SendSignedTaskResponseToAggregator.
func (mr *MockAggregatorRpcClienterMockRecorder) SendSignedTaskResponseToAggregator(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSignedTaskResponseToAggregator", reflect.TypeOf((*MockAggregatorRpcClienter)(nil).SendSignedTaskResponseToAggregator), arg0)
}
